# Generated by Django 4.2.7 on 2023-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDOApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
